export const cards = [
  { front: "/image/ace_of_spades.svg", back: "/image/reverse_side.svg", id: 1 },
  {
    front: "/image/king_of_spades.svg",
    back: "/image/reverse_side.svg",
    id: 2,
  },
  {
    front: "/image/lady_of_spades.svg",
    back: "/image/reverse_side.svg",
    id: 3,
  },
  {
    front: "/image/jack_of_spades.svg",
    back: "/image/reverse_side.svg",
    id: 4,
  },
  {
    front: "/image/ten_peaks.svg",
    back: "/image/reverse_side.svg",
    id: 5,
  },
  { front: "/image/nine_peaks.svg", back: "/image/reverse_side.svg", id: 6 },
  { front: "/image/eight_peaks.svg", back: "/image/reverse_side.svg", id: 7 },
  { front: "/image/seven_peaks.svg", back: "/image/reverse_side.svg", id: 8 },
  { front: "/image/six_peaks.svg", back: "/image/reverse_side.svg", id: 9 },
  {
    front: "/image/ace_of_hearts.svg",
    back: "/image/reverse_side.svg",
    id: 10,
  },
  {
    front: "/image/king_of_hearts.svg",
    back: "/image/reverse_side.svg",
    id: 11,
  },
  {
    front: "/image/lady_of_hearts.svg",
    back: "/image/reverse_side.svg",
    id: 12,
  },
  {
    front: "/image/jack_of_hearts.svg",
    back: "/image/reverse_side.svg",
    id: 13,
  },
  { front: "/image/ten_worms.svg", back: "/image/reverse_side.svg", id: 14 },
  { front: "/image/nine_hearts.svg", back: "/image/reverse_side.svg", id: 15 },
  { front: "/image/eight_hearts.svg", back: "/image/reverse_side.svg", id: 16 },
  {
    front: "/image/seven_hearts.svg,",
    back: "/image/reverse_side.svg",
    id: 17,
  },
  { front: "/image/six_hearts.svg", back: "/image/reverse_side.svg", id: 18 },
  {
    front: "/image/ace_of_diamonds.svg",
    back: "/image/reverse_side.svg",
    id: 19,
  },
  {
    front: "/image/king_of_diamonds.svg",
    back: "/image/reverse_side.svg",
    id: 20,
  },
  {
    front: "/image/lady_of_diamonds.svg",
    back: "/image/reverse_side.svg",
    id: 21,
  },
  {
    front: "/image/jack_of_diamonds.svg",
    back: "/image/reverse_side.svg",
    id: 22,
  },
  { front: "/image/ten_diamonds.svg", back: "/image/reverse_side.svg", id: 23 },
  {
    front: "/image/nine_diamonds.svg",
    back: "/image/reverse_side.svg",
    id: 24,
  },
  {
    front: "/image/eight_diamonds.svg",
    back: "/image/reverse_side.svg",
    id: 25,
  },
  {
    front: "/image/seven_diamonds.svg",
    back: "/image/reverse_side.svg",
    id: 26,
  },
  { front: "/image/six_diamonds.svg", back: "/image/reverse_side.svg", id: 27 },
  { front: "/image/ace_of_cross.svg", back: "/image/reverse_side.svg", id: 28 },
  {
    front: "/image/king_of_cross.svg",
    back: "/image/reverse_side.svg",
    id: 29,
  },
  {
    front: "/image/lady_of_cross.svg",
    back: "/image/reverse_side.svg",
    id: 30,
  },
  {
    front: "/image/jack_of_cross.svg",
    back: "/image/reverse_side.svg",
    id: 31,
  },
  { front: "/image/ten_crosses.svg", back: "/image/reverse_side.svg", id: 32 },
  { front: "/image/nine_crosses.svg", back: "/image/reverse_side.svg", id: 33 },
  {
    front: "/image/eight_crosses.svg",
    back: "/image/reverse_side.svg",
    id: 34,
  },
  {
    front: "/image/seven_crosses.svg",
    back: "/image/reverse_side.svg",
    id: 35,
  },
  { front: "/image/six_crosses.svg", back: "/image/reverse_side.svg", id: 32 },
];
